spring:
  application:
    name: sentinel-app1
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
    nacos:
      # nacos 服务发现
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8802