server:
  port: 8080
spring:
  application:
    name: spring-cloud-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: spring-cloud-producer-8080 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址