eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: eureka-producer-app

# 暴露健康端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,metrics
        exclude: shutdown,env,beans

  endpoint:
    health:
      # 显示详情
      show-details: always
      status:
        # 映射健康状态到HTTP状态码
        http-mapping:
          down: 500