eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: gateway-provider02-app

# 服务端口
server:
  port: 8082

# 暴露健康端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      # 显示详情
      show-details: always
      status:
        # 映射健康状态到HTTP状态码
        http-mapping:
          down: 500