spring:
  cloud:
    config:
      uri: localhost:8888
  application:
    name: myapp    #必须和gitee中文件名称一致

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      # 显示详情
      show-details: always
      status:
        # 映射健康状态到HTTP状态码
        http-mapping:
          down: 500